//
//  ColorModel.swift
//  StoryMaker
//
//  Created by devmacmini on 14/7/25.
//

import Foundation
import SwiftUI

struct Colors {
    
    static let solidColors: [String] = [
        "#FFFFFF", "#000000",
        "#742A2A", "#9B2C2C", "#C53030", "#E53E3E", "#F56565", "#FC8181", "#FEB2B2", "#FED7D7", "#FFF5F5",
        "#7B341E", "#9C4221", "#C05621", "#DD6B20", "#ED8936", "#F6AD55", "#FBD38D", "#FEEBC8", "#FFFAF0",
        "#744210", "#975A16", "#B7791F", "#D69E2E", "#ECC94B", "#F6E05E", "#FAF089", "#FEFCBF", "#FFFFF0",
        "#22543D", "#276749", "#2F855A", "#38A169", "#48BB78", "#68D391", "#9AE6B4", "#C6F6D5", "#F0FFF4",
        "#234E52", "#285E61", "#2C7A7B", "#319795", "#38B2AC", "#4FD1C5", "#81E6D9", "#B2F5EA", "#E6FFFA",
        "#2A4365", "#2C5282", "#2B6CB0", "#3182CE", "#4299E1", "#63B3ED", "#90CDF4", "#BEE3F8", "#EBF8FF",
        "#3C366B", "#434190", "#4C51BF", "#5A67D8", "#667EEA", "#7F9CF5", "#A3BFFA", "#C3DAFE", "#EBF4FF",
        "#44337A", "#553C9A", "#6B46C1", "#805AD5", "#9F7AEA", "#B794F4", "#D6BCFA", "#E9D8FD", "#FAF5FF",
        "#702459", "#97266D", "#B83280", "#D53F8C", "#ED64A6", "#F687B3", "#FBB6CE", "#FED7E2"]

    static let gradientColors: [GradientColor] = [
        GradientColor("#FF1001-#FFE5BB",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#FBB13C-#FF7A72-#FF7A72",      angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#FF5F6D-#FFC371",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#F05053-#E1EEC3",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#EF629F-#EECDA3",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#FFE29F-#FFA99F-#FF719A",      angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#FF6F61-#FDA198",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#FCF6CF-#FF886A",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#EE9CA7-#FFDDE1",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#FAD0C4-#FFD1FF",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#E3FDF5-#FFE6FA",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#FCB045-#FD1D1D-#833AB4",      angle: .leftRight,               isPremium: false),
        GradientColor("#9E1B38-#F05350",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#B31217-#E52D27",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#EB3349-#F45C43",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#FF4B2B-#FF416C",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#FF1F01-#FD5D1B-#FFC700",      angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#FF512F-#F09819",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#EC2F46-#ECD92F",              angle: .topRightBottomLeft,      isPremium: true),
        GradientColor("#FF7E5F-#FEB47B",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#FFAFBD-#FFC3A0",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#434343-#000000",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#848484-#000000",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#1E130C-#9A8478",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#B28B67-#000000",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#4F4F4F-#ECD3A1",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#119DA4-#FFE5BB-#FF886A",      angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#1E6305-#BDFF00",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#56AB2F-#A8E063",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#F09819-#EDDE5D",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#799F0C-#FFE000",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#CAC531-#F3F9A7",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#FFF06F-#FFFBD6",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#0F2027-#2C5364",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#191654-#43C6AC",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#0F3443-#34E89E",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#119DA4-#04B46D-#FBF33C",      angle: .leftRight,               isPremium: true),
        GradientColor("#11A49B-#90FC8E",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#1D6C70-#00F3FF",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#00CDAC-#02AAB0-#02AAB0",      angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#29FFC6-#20E3B2-#0CEBEB",      angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#D4FC79-#96E6A1",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#12FFF7-#B3FFAB",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#84FAB0-#8FD3F4",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#2BC0E4-#EAECC6",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#86FDE8-#ACB6E5",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#0F0C29-#0F0C29-#302B63",      angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#41295A-#2F0743",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#000000-#ACB6E5",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#5B507A-#9EADC8",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#091B6A-#0029FF",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#2C5364-#4286F4",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#0083B0-#00B4DB",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#1D2252-#72AAFF-#00FFFF",      angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#2D6DE9-#12C2E9",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#2FECEC-#4A2FEC",              angle: .topRightBottomLeft,      isPremium: false),
        GradientColor("#A7BFE8-#6190E8",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#E0EAFC-#CFDEF3",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#355C7D-#C06C84",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#3B8D99-#6B6B83-#AA4B6B",      angle: .leftRight,               isPremium: false),
        GradientColor("#E55D87-#5FC3E4",              angle: .leftRight,               isPremium: false),
        GradientColor("#8C366C-#6E64E7",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#03001E-#7303C0-#EC38BC",      angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#FF00CC-#333399",              angle: .leftRight,               isPremium: false),
        GradientColor("#DA22FF-#9733EE",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#FDEFF9-#EC38BC-#7303C0",      angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#F64F59-#C471ED-#12C2E9",      angle: .leftRight,               isPremium: true),
        GradientColor("#6A82FB-#FC5C7D",              angle: .leftRight,               isPremium: true),
        GradientColor("#EC6EAD-#3494E6",              angle: .leftRight,               isPremium: false),
        GradientColor("#CB3066-#16BFFD",              angle: .leftRight,               isPremium: true),
        GradientColor("#89FFFD-#EF32D9",              angle: .leftRight,               isPremium: true),
        GradientColor("#ECA1FE-#5271C4-#5271C4",      angle: .topBottom,               isPremium: true),
        GradientColor("#FDB99B-#CF8BF3-#A770EF",      angle: .leftRight,               isPremium: true),
        GradientColor("#A18CD1-#FBC2EB",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#A6C1EE-#FBC2EB",              angle: .topBottom,               isPremium: false),
        GradientColor("#E9E4F0-#D3CCE3",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#EEEDF1-#FFFFFF",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#61045F-#AA076B",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#601343-#F4528D",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#620F32-#FF149D",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#BC4E9C-#F80759",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#D70652-#FF025E",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#DD2FEC-#EC2F2F",              angle: .topRightBottomLeft,      isPremium: false),
        GradientColor("#904E95-#E96443",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#CA2888-#D38282",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#BA5370-#F4E2D8",              angle: .topLeftBottomRight,      isPremium: false),
        GradientColor("#ACB4E7-#B1E0B0",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#B9E28C-#FFA5FF",              angle: .topLeftBottomRight,      isPremium: true),
        GradientColor("#FC67FA-#F4C4F3",              angle: .topLeftBottomRight,      isPremium: false)
    ]
}
