//
//  Fonts.swift
//  StoryMaker
//
//  Created by devmacmini on 11/7/25.
//

import Foundation

enum FontCategory: String {
    case serif = "Serif"
    case sansSerif = "Sans Serif"
    case display = "Display"
    case monospace = "Monospace"
    case handwriting = "Handwriting"
}

struct CFont : Hashable {
    var category: FontCategory
    var family: String
    var iosFamily: String
    var isPremium: Bool = false
    
    init(_ category: FontCategory, family: String, ios: String, isPremium: Bool) {
        self.category = category
        self.family = family
        self.iosFamily = ios
        self.isPremium = isPremium
    }
    
    static let categories: [FontCategory] = [
        .serif,
        .sansSerif,
        .display,
        .monospace,
        .handwriting,
    ]
    
    static let fonts: [CFont] = [
        CFont(.serif,                   family: "",                                           ios: "Aesthetic",                                           isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "against",                                             isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Aghisna Display",                                     isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Alcantera",                                           isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "American Frights",                                    isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Angelissa",                                           isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Asteria",                                             isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Bartolomew",                                          isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "BioRhyme Expanded",                                   isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Bochan Serif",                                        isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Boiling Demo",                                        isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Brand",                                               isPremium: true),
        CFont(.serif,                   family: "Brighton vintage",                           ios: "brighton vintage",                                    isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Bristol maver",                                       isPremium: true),
        CFont(.serif,                   family: "Cafollas Demo",                              ios: "Cafollas Demo",                                       isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Cheria",                                              isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Degila",                                              isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Diezma Rd",                                           isPremium: false),
        CFont(.serif,                   family: "Doppelganger",                               ios: "Doppelganger Display",                                isPremium: true),
        CFont(.serif,                   family: "Emerland",                                   ios: "emerland",                                            isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Erica Type",                                          isPremium: false),
        CFont(.serif,                   family: "Excrallik",                                  ios: "excrallik",                                           isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Fredella",                                            isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Giveny",                                              isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Glory Sunshine",                                      isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Godan",                                               isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Gold&Song",                                           isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Sandome__G",                                          isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Great Victorian",                                     isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Gufin",                                               isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "HONZO",                                               isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Janji Neue",                                          isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Jim Alistair Demo",                                   isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "JuneMorning",                                         isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "KARA",                                                isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Kingkey Demo",                                        isPremium: false),
        CFont(.serif,                   family: "Le Jour",                                    ios: "Le Jour",                                             isPremium: false),
        CFont(.serif,                   family: "Lovelace Text",                              ios: "Lovelace Text",                                       isPremium: false),
        CFont(.serif,                   family: "Lovelace Text-Bold-Italic",                  ios: "Lovelace Text Bold Italic",                           isPremium: false),
        CFont(.serif,                   family: "Lora",                                       ios: "Lora",                                                isPremium: false),
        CFont(.serif,                   family: "Lora-Italic",                                ios: "Lora Italic",                                         isPremium: false),
        CFont(.serif,                   family: "Lora-Medium",                                ios: "Lora Medium",                                         isPremium: false),
        CFont(.serif,                   family: "Lora-Medium-Italic",                         ios: "Lora Medium Italic",                                  isPremium: false),
        CFont(.serif,                   family: "Lora-SemiBold",                              ios: "Lora SemiBold",                                       isPremium: false),
        CFont(.serif,                   family: "Lora-SemiBold-Italic",                       ios: "Lora SemiBold Italic",                                isPremium: false),
        CFont(.serif,                   family: "Lora-Bold",                                  ios: "Lora Bold",                                           isPremium: false),
        CFont(.serif,                   family: "Lora-Bold-Italic",                           ios: "Lora Bold Italic",                                    isPremium: false),
        CFont(.serif,                   family: "Maaz",                                       ios: "maaz",                                                isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "MADE Dillan",                                         isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Magic Sparkle",                                       isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "magoa",                                               isPremium: false),
        CFont(.serif,                   family: "Martel-Extra-Light",                         ios: "Martel UltraLight",                                   isPremium: false),
        CFont(.serif,                   family: "Martel-Light",                               ios: "Martel Light",                                        isPremium: false),
        CFont(.serif,                   family: "Martel",                                     ios: "Martel",                                              isPremium: false),
        CFont(.serif,                   family: "Martel-Semi-Bold",                           ios: "Martel DemiBold",                                     isPremium: false),
        CFont(.serif,                   family: "Martel-Bold",                                ios: "Martel Bold",                                         isPremium: false),
        CFont(.serif,                   family: "Martel-Extra-Bold",                          ios: "Martel ExtraBold",                                    isPremium: false),
        CFont(.serif,                   family: "Martel-Black",                               ios: "Martel Heavy",                                        isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Malito Fashion",                                      isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Maroon black",                                        isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Marquise",                                            isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Matchbook Serif",                                     isPremium: false),
        CFont(.serif,                   family: "Mazreha",                                    ios: "Mazreha",                                             isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Men Nefer",                                           isPremium: false),
        CFont(.serif,                   family: "Mercy Christole",                            ios: "mercy christole",                                     isPremium: true),
        CFont(.serif,                   family: "Monalisa Serif",                             ios: "monalisa serif",                                      isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Nomark",                                              isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Nostalgia",                                           isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Opulent Demo",                                        isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Pitch Display",                                       isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Qalisha Signature Serif",                             isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Rahgbok",                                             isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Remish",                                              isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Renaisans",                                           isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Robecha Daniera",                                     isPremium: false),
        CFont(.serif,                   family: "Rokkitt-Thin",                               ios: "Rokkitt-Thin",                                        isPremium: false),
        CFont(.serif,                   family: "Rokkitt",                                    ios: "Rokkitt-Regular",                                     isPremium: false),
        CFont(.serif,                   family: "Rokkitt-Medium",                             ios: "Rokkitt-Medium",                                      isPremium: false),
        CFont(.serif,                   family: "Rokkitt-SemiBold",                           ios: "Rokkitt-SemiBold",                                    isPremium: false),
        CFont(.serif,                   family: "Rokkitt-Bold",                               ios: "Rokkitt-Bold",                                        isPremium: false),
        CFont(.serif,                   family: "Rokkitt-ExtraBold",                          ios: "Rokkitt-ExtraBold",                                   isPremium: false),
        CFont(.serif,                   family: "Rokkitt-Black",                              ios: "Rokkitt-Black",                                       isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "ROLLINA",                                             isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Yaribe",                                              isPremium: true),
        CFont(.serif,                   family: "Rusilla serif",                              ios: "rusilla serif",                                       isPremium: false),
        CFont(.serif,                   family: "Sinoreta Personal Use",                      ios: "Sinoreta Personal Use",                               isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Skinner Morgan",                                      isPremium: true),
        CFont(.serif,                   family: "",                                           ios: "Solerin Magica",                                      isPremium: true),
        CFont(.serif,                   family: "Spectre",                                    ios: "spectre",                                             isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Tefis Regular",                                       isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Trirong",                                             isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Ultra",                                               isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Umba Slab Demo",                                      isPremium: false),
        CFont(.serif,                   family: "Unna",                                       ios: "Unna-Regular",                                        isPremium: false),
        CFont(.serif,                   family: "Unna-Italic",                                ios: "Unna-Italic",                                         isPremium: false),
        CFont(.serif,                   family: "Unna-Bold",                                  ios: "Unna-Bold",                                           isPremium: false),
        CFont(.serif,                   family: "Unna-BoldItalic",                            ios: "Unna-BoldItalic",                                     isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Viorath",                                             isPremium: false),
        CFont(.serif,                   family: "Whimster Glympse Demo",                      ios: "whimsterglympsedemo",                                 isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Words Taken Demo",                                    isPremium: false),
        CFont(.serif,                   family: "",                                           ios: "Yanking",                                             isPremium: false),
        
        CFont(.sansSerif,               family: "Akuina Personal use",                        ios: "AkuinaPersonaluse-ExtraBold",                         isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Alba Matter",                                         isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "B612 Regular",                                        isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Bakole Regatoni",                                     isPremium: false),
        CFont(.sansSerif,               family: "Balbek Personal Use Only",                   ios: "balbek personal use only",                            isPremium: false),
        CFont(.sansSerif,               family: "Bambina",                                    ios: "Bambina Regular",                                     isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Basaro",                                              isPremium: true),
        CFont(.sansSerif,               family: "Bloviate Demo",                              ios: "BloviateDemoRegular",                                 isPremium: false),
        CFont(.sansSerif,               family: "Botes",                                      ios: "botes",                                               isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Break Resbonger",                                     isPremium: false),
        CFont(.sansSerif,               family: "Breaked",                                    ios: "breaked",                                             isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Brobrq",                                              isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Bronix",                                              isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Candle",                                              isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Cano",                                                isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Carrinady",                                           isPremium: false),
        CFont(.sansSerif,               family: "Cissele",                                    ios: "cissele",                                             isPremium: true),
        CFont(.sansSerif,               family: "Comic Neue",                                 ios: "ComicNeue-Regular",                                   isPremium: false),
        CFont(.sansSerif,               family: "Comic Neue-Light",                           ios: "ComicNeue-Light",                                     isPremium: false),
        CFont(.sansSerif,               family: "Comic Neue-Bold",                            ios: "ComicNeue-Bold",                                      isPremium: false),
        CFont(.sansSerif,               family: "Coolvetica",                                 ios: "coolvetica",                                          isPremium: true),
        CFont(.sansSerif,               family: "Cottsmic",                                   ios: "cottsmic",                                            isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "CRENZO",                                              isPremium: false),
        CFont(.sansSerif,               family: "Defoils",                                    ios: "defoils",                                             isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Delight",                                             isPremium: false),
        CFont(.sansSerif,               family: "DMSans-Thin",                                ios: "DMSans-Thin",                                         isPremium: false),
        CFont(.sansSerif,               family: "DMSans-ThinItalic",                          ios: "DMSans-ThinItalic",                                   isPremium: false),
        CFont(.sansSerif,               family: "DMSans-Light",                               ios: "DMSans-Light",                                        isPremium: false),
        CFont(.sansSerif,               family: "DMSans-LightItalic",                         ios: "DMSans-LightItalic",                                  isPremium: false),
        CFont(.sansSerif,               family: "DMSans-ExtraLight",                          ios: "DMSans-ExtraLight",                                   isPremium: false),
        CFont(.sansSerif,               family: "DMSans-ExtraLightItalic",                    ios: "DMSans-ExtraLightItalic",                             isPremium: false),
        CFont(.sansSerif,               family: "DMSans",                                     ios: "DMSans-Regular",                                      isPremium: false),
        CFont(.sansSerif,               family: "DMSans-Italic",                              ios: "DMSans-Italic",                                       isPremium: false),
        CFont(.sansSerif,               family: "DMSans-Medium",                              ios: "DMSans-Medium",                                       isPremium: false),
        CFont(.sansSerif,               family: "DMSans-MediumItalic",                        ios: "DMSans-MediumItalic",                                 isPremium: false),
        CFont(.sansSerif,               family: "DMSans-SemiBold",                            ios: "DMSans-SemiBold",                                     isPremium: false),
        CFont(.sansSerif,               family: "DMSans-SemiBoldItalic",                      ios: "DMSans-SemiBoldItalic",                               isPremium: false),
        CFont(.sansSerif,               family: "DMSans-Bold",                                ios: "DMSans-Bold",                                         isPremium: false),
        CFont(.sansSerif,               family: "DMSans-BoldItalic",                          ios: "DMSans-BoldItalic",                                   isPremium: false),
        CFont(.sansSerif,               family: "DMSans-ExtraBold",                           ios: "DMSans-ExtraBold",                                    isPremium: false),
        CFont(.sansSerif,               family: "DMSans-ExtraBoldItalic",                     ios: "DMSans-ExtraBoldItalic",                              isPremium: false),
        CFont(.sansSerif,               family: "DMSans-Black",                               ios: "DMSans-Black",                                        isPremium: false),
        CFont(.sansSerif,               family: "DMSans-BlackItalic",                         ios: "DMSans-BlackItalic",                                  isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Donne",                                               isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Eagon",                                               isPremium: true),
        CFont(.sansSerif,               family: "Enoway",                                     ios: "enoway-oblique",                                      isPremium: true),
        CFont(.sansSerif,               family: "Exo",                                        ios: "Exo-ExtraBold",                                       isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Flycatcher",                                          isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Flying Sneakers",                                     isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Fonseca",                                             isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Fontspring DEMO - cera round pro medium",             isPremium: true),
        CFont(.sansSerif,               family: "Fuzzy Bubbles",                              ios: "FuzzyBubbles-Regular",                                isPremium: false),
        CFont(.sansSerif,               family: "Gayathri-Thin",                              ios: "Gayathri-Thin",                                       isPremium: false),
        CFont(.sansSerif,               family: "Gayathri",                                   ios: "Gayathri-Regular",                                    isPremium: false),
        CFont(.sansSerif,               family: "Gayathri-Bold",                              ios: "Gayathri-Bold",                                       isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Geliano",                                             isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Govers",                                              isPremium: true),
        CFont(.sansSerif,               family: "Gratelos",                                   ios: "gratelosdisplay",                                     isPremium: false),
        CFont(.sansSerif,               family: "Greenos",                                    ios: "greenos",                                             isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Gundam",                                              isPremium: true),
        CFont(.sansSerif,               family: "Hanover",                                    ios: "Hanover-Light",                                       isPremium: false),
        CFont(.sansSerif,               family: "Harmonias Demo",                             ios: "HarmoniasDemoRegular",                                isPremium: false),
        CFont(.sansSerif,               family: "Heebo",                                      ios: "Heebo",                                               isPremium: false),
        CFont(.sansSerif,               family: "Heebo-Bold",                                 ios: "Heebo Bold",                                          isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Hegimeda",                                            isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Helios Rounded",                                      isPremium: false),
        CFont(.sansSerif,               family: "Helios",                                     ios: "helios-bold",                                         isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Heroum",                                              isPremium: true),
        CFont(.sansSerif,               family: "Herova",                                     ios: "Herova-Regular",                                      isPremium: false),
        CFont(.sansSerif,               family: "Highdream",                                  ios: "Highdream-Bold",                                      isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Hiylard",                                             isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Ignotum",                                             isPremium: true),
        CFont(.sansSerif,               family: "Jack Lane",                                  ios: "jack lane",                                           isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Jipgosek",                                            isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Katoria Sans",                                        isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Kolgimba",                                            isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Langrove",                                            isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "LARUDE",                                              isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Lebrone",                                             isPremium: true),
        CFont(.sansSerif,               family: "Light Sans Serif 7",                         ios: "light sans serif 7",                                  isPremium: false),
        CFont(.sansSerif,               family: "Lilard",                                     ios: "lilard",                                              isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Linnett",                                             isPremium: false),
        CFont(.sansSerif,               family: "Lumber",                                     ios: "Lumber-Regular",                                      isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "MADE Tommy Soft",                                     isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Maftuh",                                              isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "MAREGY",                                              isPremium: false),
        CFont(.sansSerif,               family: "Metrofutura",                                ios: "metrofutura",                                         isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Metroland",                                           isPremium: true),
        CFont(.sansSerif,               family: "Micker",                                     ios: "micker",                                              isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-Thin",                            ios: "Montserrat-Thin",                                     isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-ThinItalic",                      ios: "Montserrat-ThinItalic",                               isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-Light",                           ios: "Montserrat-Light",                                    isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-LightItalic",                     ios: "Montserrat-LightItalic",                              isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-ExtraLight",                      ios: "Montserrat-ExtraLight",                               isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-ExtraLightItalic",                ios: "Montserrat-ExtraLightItalic",                         isPremium: false),
        CFont(.sansSerif,               family: "Montserrat",                                 ios: "Montserrat-Regular",                                  isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-Italic",                          ios: "Montserrat-Italic",                                   isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-Medium",                          ios: "Montserrat-Medium",                                   isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-MediumItalic",                    ios: "Montserrat-MediumItalic",                             isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-SemiBold",                        ios: "Montserrat-SemiBold",                                 isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-SemiBoldItalic",                  ios: "Montserrat-SemiBoldItalic",                           isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-Bold",                            ios: "Montserrat-Bold",                                     isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-BoldItalic",                      ios: "Montserrat-BoldItalic",                               isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-ExtraBold",                       ios: "Montserrat-ExtraBold",                                isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-ExtraBoldItalic",                 ios: "Montserrat-ExtraBoldItalic",                          isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-Black",                           ios: "Montserrat-Black",                                    isPremium: false),
        CFont(.sansSerif,               family: "Montserrat-BlackItalic",                     ios: "Montserrat-BlackItalic",                              isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Point DEMO",                                          isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Point Soft DEMO",                                     isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "NIght Space",                                         isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Noguf",                                               isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Microsoft New Tai Lue",                               isPremium: false),
        CFont(.sansSerif,               family: "Microsoft New Tai Lue-Bold",                 ios: "Microsoft New Tai Lue Bold",                          isPremium: false),
        CFont(.sansSerif,               family: "Primer",                                     ios: "primer",                                              isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Qasbyne",                                             isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Quentin_Pro",                                         isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Quostige",                                            isPremium: true),
        CFont(.sansSerif,               family: "Ratual",                                     ios: "ratual",                                              isPremium: true),
        CFont(.sansSerif,               family: "RedFive",                                    ios: "REDFIVE",                                             isPremium: false),
        CFont(.sansSerif,               family: "RedHatText-Light",                           ios: "Red Hat Text Light",                                  isPremium: false),
        CFont(.sansSerif,               family: "RedHatText-Light-Italic",                    ios: "Red Hat Text Light Italic",                           isPremium: false),
        CFont(.sansSerif,               family: "RedHatText",                                 ios: "Red Hat Text",                                        isPremium: false),
        CFont(.sansSerif,               family: "RedHatText-Italic",                          ios: "Red Hat Text Italic",                                 isPremium: false),
        CFont(.sansSerif,               family: "RedHatText-Medium",                          ios: "Red Hat Text Medium",                                 isPremium: false),
        CFont(.sansSerif,               family: "RedHatText-Medium-Italic",                   ios: "Red Hat Text Medium Italic",                          isPremium: false),
        CFont(.sansSerif,               family: "RedHatText-SemiBold",                        ios: "Red Hat Text SemiBold",                               isPremium: false),
        CFont(.sansSerif,               family: "RedHatText-SemiBold-Italic",                 ios: "Red Hat Text SemiBold Italic",                        isPremium: false),
        CFont(.sansSerif,               family: "RedHatText-Bold",                            ios: "Red Hat Text Bold",                                   isPremium: false),
        CFont(.sansSerif,               family: "RedHatText-Bold-Italic",                     ios: "Red Hat Text Bold Italic",                            isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Reef",                                                isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Restiany",                                            isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-Thin",                                         isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-ThinItalic",                                   isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-Light",                                        isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-LightItalic",                                  isPremium: false),
        CFont(.sansSerif,               family: "Roboto",                                     ios: "Roboto-Regular",                                      isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-Italic",                                       isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-Medium",                                       isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-MediumItalic",                                 isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-Bold",                                         isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-BoldItalic",                                   isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-Black",                                        isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Roboto-BlackItalic",                                  isPremium: false),
        CFont(.sansSerif,               family: "Roboto Condensed",                           ios: "RobotoCondensed-Regular",                             isPremium: false),
        CFont(.sansSerif,               family: "Roboto Condensed-Bold",                      ios: "RobotoCondensed-Bold",                                isPremium: false),
        CFont(.sansSerif,               family: "Roboto Condensed-Italic",                    ios: "RobotoCondensed-BoldItalic",                          isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Rocky Display",                                       isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Sagres",                                              isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Sajola",                                              isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Sasvac",                                              isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "savec",                                               isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Smart Schools",                                       isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Smooch Sans",                                         isPremium: true),
        CFont(.sansSerif,               family: "Souci Sans NF",                              ios: "SouciSansNF",                                         isPremium: true),
        CFont(.sansSerif,               family: "Strasua",                                    ios: "strasua",                                             isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Suissnord",                                           isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Tangsel",                                             isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Thousand Lake",                                       isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Trifelia",                                            isPremium: true),
        CFont(.sansSerif,               family: "unaria",                                     ios: "Unaria",                                              isPremium: true),
        CFont(.sansSerif,               family: "Waylimo",                                    ios: "waylimo",                                             isPremium: true),
        CFont(.sansSerif,               family: "",                                           ios: "Wermland Gothic",                                     isPremium: false),
        CFont(.sansSerif,               family: "",                                           ios: "Wostelkan",                                           isPremium: false),
        CFont(.sansSerif,               family: "Zenzero Grotesk Sans",                       ios: "ZenzeroGroteskSans-Round",                            isPremium: true),
                
        CFont(.display,                 family: "AmaticSC",                                   ios: "AmaticSC-Regular",                                    isPremium: false),
        CFont(.display,                 family: "AmaticSC-Bold",                              ios: "AmaticSC-Bold",                                       isPremium: false),
        CFont(.display,                 family: "Back to 1982",                               ios: "BACKTO1982",                                          isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Barbed Wires",                                        isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Bates Shower",                                        isPremium: false),
        CFont(.display,                 family: "",                                           ios: "BlackWidow",                                          isPremium: false),
        CFont(.display,                 family: "Blood Lust",                                 ios: "BloodLust",                                           isPremium: true),
        CFont(.display,                 family: "Butterfly Kids",                             ios: "Butterfly Kids",                                      isPremium: false),
        CFont(.display,                 family: "Cattie",                                     ios: "Cattie-Regular",                                      isPremium: false),
        CFont(.display,                 family: "",                                           ios: "CattyFunny",                                          isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Curely",                                              isPremium: false),
        CFont(.display,                 family: "",                                           ios: "December Holidays",                                   isPremium: false),
        CFont(.display,                 family: "Defence War",                                ios: "DefenceWar-Regular",                                  isPremium: true),
        CFont(.display,                 family: "",                                           ios: "DiceGameDEMO",                                        isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Doppelganger",                                        isPremium: true),
        CFont(.display,                 family: "",                                           ios: "Elivia",                                              isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Frightmare",                                          isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Game Shark",                                          isPremium: true),
        CFont(.display,                 family: "Halloween Story",                            ios: "HALLOWEEN STORY",                                     isPremium: false),
        CFont(.display,                 family: "Hanging Tree Staggered Rotalic",             ios: "HangingTreeStaggeredRotalic",                         isPremium: false),
        CFont(.display,                 family: "",                                           ios: "HeavenGate",                                          isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Insomnia",                                            isPremium: true),
        CFont(.display,                 family: "Janda Hide And Seek",                        ios: "JandaHideAndSeek",                                    isPremium: false),
        CFont(.display,                 family: "Kranky",                                     ios: "Kranky-Regular",                                      isPremium: false),
        CFont(.display,                 family: "",                                           ios: "maria",                                               isPremium: false),
        CFont(.display,                 family: "Monoton",                                    ios: "Monoton-Regular",                                     isPremium: true),
        CFont(.display,                 family: "",                                           ios: "Monstrocity",                                         isPremium: false),
        CFont(.display,                 family: "",                                           ios: "MosaicCaps",                                          isPremium: true),
        CFont(.display,                 family: "Mountains of Christmas",                     ios: "MountainsofChristmas-Regular",                        isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Nervous",                                             isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Plante",                                              isPremium: true),
        CFont(.display,                 family: "Plasma Drip Empty BRK",                      ios: "PlasmaDripEmptyBRK",                                  isPremium: false),
        CFont(.display,                 family: "",                                           ios: "PUPPY LOVE BRUSH",                                    isPremium: true),
        CFont(.display,                 family: "Refunk",                                     ios: "refunk-blackfree",                                    isPremium: true),
        CFont(.display,                 family: "",                                           ios: "Run! Demo",                                           isPremium: false),
        CFont(.display,                 family: "",                                           ios: "RUSTY ATTACK DEMO",                                   isPremium: false),
        CFont(.display,                 family: "Saevul",                                     ios: "saevul",                                              isPremium: true),
        CFont(.display,                 family: "Scary Forest",                               ios: "scary forest",                                        isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Scizzorwreck Halbfett",                               isPremium: true),
        CFont(.display,                 family: "",                                           ios: "Sengatz",                                             isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Snowby",                                              isPremium: false),
        CFont(.display,                 family: "",                                           ios: "StripesCaps",                                         isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Sweet Husky",                                         isPremium: false),
        CFont(.display,                 family: "Tape Rail",                                  ios: "taperail-regular",                                    isPremium: false),
        CFont(.display,                 family: "",                                           ios: "TastyDrips",                                          isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Tasy Tuwek",                                          isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Thalassophobia-Demo",                                 isPremium: false),
        CFont(.display,                 family: "",                                           ios: "THE CREEPY HUNTER",                                   isPremium: true),
        CFont(.display,                 family: "Thorletto",                                  ios: "Thorletto (free)",                                    isPremium: false),
        CFont(.display,                 family: "Toys Shadow",                                ios: "ToysShadow-regular",                                  isPremium: false),
        CFont(.display,                 family: "",                                           ios: "Varvara",                                             isPremium: true),
        CFont(.display,                 family: "",                                           ios: "Warbones",                                            isPremium: false),
        CFont(.display,                 family: "Words of love",                              ios: "WORDSOFLOVE",                                         isPremium: true),
        
        CFont(.monospace,               family: "CamingoCode",                                ios: "CamingoCode-Regular",                                 isPremium: true),
        CFont(.monospace,               family: "",                                           ios: "Anonymous Pro",                                       isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Azeret Mono",                                         isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Azeret Mono Thin",                                    isPremium: false),
        CFont(.monospace,               family: "B612 Mono",                                  ios: "B612Mono-Regular",                                    isPremium: true),
        CFont(.monospace,               family: "",                                           ios: "Bitstream Vera Sans Mono",                            isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "BPmono",                                              isPremium: false),
        CFont(.monospace,               family: "Consola Mono",                               ios: "ConsolaMono-Book",                                    isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Courier New",                                         isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Courier Prime",                                       isPremium: false),
        CFont(.monospace,               family: "Cousine",                                    ios: "Cousine-Regular",                                     isPremium: false),
        CFont(.monospace,               family: "DejaVu Sans Mono",                           ios: "DejaVuSansMono-BoldOblique",                          isPremium: false),
        CFont(.monospace,               family: "Darker Grotesque-Light",                     ios: "DarkerGrotesque-Light",                               isPremium: false),
        CFont(.monospace,               family: "Darker Grotesque-Regular",                   ios: "DarkerGrotesque-Regular",                             isPremium: false),
        CFont(.monospace,               family: "Darker Grotesque-Medium",                    ios: "DarkerGrotesque-Medium",                              isPremium: false),
        CFont(.monospace,               family: "Darker Grotesque-SemiBold",                  ios: "DarkerGrotesque-SemiBold",                            isPremium: false),
        CFont(.monospace,               family: "Darker Grotesque-Bold",                      ios: "DarkerGrotesque-Bold",                                isPremium: false),
        CFont(.monospace,               family: "Darker Grotesque-Black",                     ios: "DarkerGrotesque-Black",                               isPremium: false),
        CFont(.monospace,               family: "Darker Grotesque-ExtraBold",                 ios: "DarkerGrotesque-ExtraBold",                           isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "DPSDbeyond",                                          isPremium: true),
        CFont(.monospace,               family: "Droid Sans Mono",                            ios: "DroidSansMono",                                       isPremium: false),
        CFont(.monospace,               family: "Fantasque Sans Mono",                        ios: "fantasquesansmono-regular",                           isPremium: true),
        CFont(.monospace,               family: "",                                           ios: "Hack",                                                isPremium: false),
        CFont(.monospace,               family: "iA Writer Duospace",                         ios: "iAWriterDuospace-Regular",                            isPremium: false),
        CFont(.monospace,               family: "IBM Plex Mono",                              ios: "IBMPlexMono-Regular",                                 isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Inconsolata",                                         isPremium: true),
        CFont(.monospace,               family: "",                                           ios: "Instruction",                                         isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-Thin",                         ios: "JetBrainsMono-Thin",                                  isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-ThinItalic",                   ios: "JetBrainsMono-ThinItalic",                            isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-ExtraLight",                   ios: "JetBrainsMono-ExtraLight",                            isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-ExtraLightItalic",             ios: "JetBrainsMono-ExtraLightItalic",                      isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-Light",                        ios: "JetBrainsMono-Light",                                 isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-LightItalic",                  ios: "JetBrainsMono-LightItalic",                           isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-Regular",                      ios: "JetBrainsMono-Regular",                               isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-Italic",                       ios: "JetBrainsMono-Italic",                                isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-Medium",                       ios: "JetBrainsMono-Medium",                                isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-MediumItalic",                 ios: "JetBrainsMono-MediumItalic",                          isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-SemiBold",                     ios: "JetBrainsMono-SemiBold",                              isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-SemiBoldItalic",               ios: "JetBrainsMono-SemiBoldItalic",                        isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-Bold",                         ios: "JetBrainsMono-Bold",                                  isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-BoldItalic",                   ios: "JetBrainsMono-BoldItalic",                            isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-ExtraBold",                    ios: "JetBrainsMono-ExtraBold",                             isPremium: false),
        CFont(.monospace,               family: "JetBrainsMono-ExtraBoldItalic",              ios: "JetBrainsMono-ExtraBoldItalic",                       isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Manti Sans Fixed Demo",                               isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Martian Mono",                                        isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "monofonto",                                           isPremium: true),
        CFont(.monospace,               family: "Nimbus Mono",                                ios: "NimbusMono-BoldOblique",                              isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "nk57 monospace",                                      isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Noguf",                                               isPremium: true),
        CFont(.monospace,               family: "",                                           ios: "PT Mono",                                             isPremium: true),
        CFont(.monospace,               family: "",                                           ios: "Sansation Light",                                     isPremium: false),
        CFont(.monospace,               family: "Simply Mono",                                ios: "SimplyMono-Bold",                                     isPremium: true),
        CFont(.monospace,               family: "Sometype Mono",                              ios: "SometypeMono-Medium",                                 isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Source Code Pro",                                     isPremium: false),
        CFont(.monospace,               family: "Space Mono",                                 ios: "SpaceMono-BoldItalic",                                isPremium: true),
        CFont(.monospace,               family: "Space Mono",                                 ios: "SpaceMono-Regular",                                   isPremium: true),
        CFont(.monospace,               family: "",                                           ios: "Spline Sans Mono",                                    isPremium: false),
        CFont(.monospace,               family: "",                                           ios: "Targa",                                               isPremium: true),
        CFont(.monospace,               family: "TeX Gyre Cursor",                            ios: "texgyrecursor-regular",                               isPremium: false),
        CFont(.monospace,               family: "Ubuntu Mono",                                ios: "UbuntuMono-Regular",                                  isPremium: false),
        CFont(.monospace,               family: "Unispace",                                   ios: "unispace",                                            isPremium: false),
        CFont(.monospace,               family: "Xanh Mono",                                  ios: "XanhMono-Regular",                                    isPremium: false),
        
        CFont(.handwriting,             family: "",                                           ios: "Aventurine",                                          isPremium: false),
        CFont(.handwriting,             family: "Astetica",                                   ios: "astetica",                                            isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Ashytha",                                             isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Arion Typeface",                                      isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Annette Bradford DEMO",                               isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Angel Cry",                                           isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Andora",                                              isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Amarula Personal Use",                                isPremium: true),
        CFont(.handwriting,             family: "Amandave Signature",                         ios: "AmandaveSignature-Regular",                           isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Allison Tessa",                                       isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Aksana",                                              isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Airin",                                               isPremium: true),
        CFont(.handwriting,             family: "aaAaleyah_PersonalUseOnly",                  ios: "Aaleyah_PersonalUseOnly",                             isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Babymom",                                             isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Backstreet",                                          isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Bargiery",                                            isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Bastliga One",                                        isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Bathedya",                                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Beauty One",                                          isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Bettina Signature",                                   isPremium: true),
        CFont(.handwriting,             family: "Blaster",                                    ios: "blaster",                                             isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Blues Malone",                                        isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Bluettelli",                                          isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Bonithy Rossela",                                     isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Boomolla",                                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "BreceletsDemo",                                       isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Bridetown",                                           isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Broetown Signature",                                  isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Catthy Wellingten",                                   isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Christmasfest",                                       isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Concetta Kalvani",                                    isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Darlington Demo",                                     isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Dollamin",                                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "DreamCatchersDemo",                                   isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Emily Yorke",                                         isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Emitanela",                                           isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Estermoon",                                           isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Foundry Font Pack",                                   isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Frankie Twist",                                       isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Geovana",                                             isPremium: false),
        CFont(.handwriting,             family: "Hand Signature Demo",                        ios: "HandSignatureDemoRegular",                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Hello Glow",                                          isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Helttox Brush",                                       isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Holland",                                             isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Honeymoon Avenue Script",                             isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Jacky Black Trial",                                   isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Jhon Wave",                                           isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Kallem",                                              isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Maldives",                                            isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Mantilda Kristine",                                   isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Mashita",                                             isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Meilleur",                                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Moscato",                                             isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Paradise Sunset - Perosnal Use",                      isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Parallove",                                           isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Rafaela Grante",                                      isPremium: false),
        CFont(.handwriting,             family: "Reallishmy",                                 ios: "reallishmy",                                          isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Reinatha",                                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Reman",                                               isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Roger Heart",                                         isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Rohana",                                              isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Roschelle",                                           isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Salmander Bentols Script",                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Santeria Signature",                                  isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Satherday - Personal Use",                            isPremium: true),
        CFont(.handwriting,             family: "Scriptina",                                  ios: "SCRIPTINA",                                           isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Siestha",                                             isPremium: false),
        CFont(.handwriting,             family: "Signature Forest",                           ios: "signatureforest",                                     isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Sincere Valentine - PERSONAL US",                     isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Singeldust",                                          isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Sintya FREE",                                         isPremium: false),
        CFont(.handwriting,             family: "Skintone",                                   ios: "skintone",                                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Southam Demo",                                        isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Stanford Signature",                                  isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "StephenGillion DEMO",                                 isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Sundaytime",                                          isPremium: true),
        CFont(.handwriting,             family: "The flash",                                  ios: "the flash",                                           isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "The Illusion of Beauty",                              isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "The Suavity",                                         isPremium: true),
        CFont(.handwriting,             family: "",                                           ios: "Travelisty",                                          isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Undercut",                                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Urban Signature",                                     isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Veltloved",                                           isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Westerny Barnett",                                    isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Westie Ametta",                                       isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Westonia",                                            isPremium: false),
        CFont(.handwriting,             family: "",                                           ios: "Youth Syndicate",                                     isPremium: true),
    ]
}
